compiler: ghc-7.10.2
resolver: nightly-2016-05-13
system-ghc: false
install-ghc: true
packages:
- '.'
- location:
    git: git@github.com:iconnect/github.git
    commit: "06f5112344fce5cba831cc71cdcf7fc5320112c8"
extra-deps: []
flags: {}
extra-package-dbs: []
